{
 "title": "{ //todo replace }",
 "description": "United dashboard for { //todo replace }",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "dev2,prod, prod2" },
   {
    "name": "namespace",
    "query": "pql label_values(kube_deployment_labels{namespace=~\"{ //todo replace }.*\",env=~\"$env|$dc-$env\",group=\"k8s\"},namespace)"
   },
   {
    "name": "applicationName",
    "label": "service",
    "query": "pql label_values(kube_pod_labels{env=~\"$env|$dc-$env\",namespace=~\"$namespace.*\",group=\"k8s\"},label_app)"
   },
   { "name": "dc", "query": "ds,m1" },
   {
    "name": "podName",
    "query": "pql label_values(kube_pod_info{k8scluster=~\"$env|$dc-$env\",namespace=\"$namespace\",pod_name=~\"$dc-$applicationName.*|$applicationName.*\"},pod_name) "
   },
   {
    "name": "db",
    "query": "pql label_values(jdbc_connections_min{env=~\"$env|$dc-$env\",group=\"$namespace\",container_name=~\"$applicationName|\", service =~ \"$applicationName-metrics|\"}, name)"
   },
   { "name": "interval", "query": "20s,30s,1m,5m,10m,30m,1h" },
   { "name": "quantile", "query": "0.5,0.7,0.9,0.95,0.99,0.999" }
  ]
 },
 "panels": [
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "latency (sec) http/logic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(method_timed_seconds_bucket{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\", env=\"$env\"}[1m])) by (operationName, dc, pod_name, le))",
     "legendFormat": "[{{pod_name}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "http_server_requests_seconds{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\",  quantile=\"$quantile\"}  ",
     "legendFormat": "[{{pod_name}}] {{operationName}}  {{uri}} ",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "method_timed_seconds{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\", quantile=\"$quantile\"}",
     "legendFormat": "[{{pod_name}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(http_server_requests_seconds_bucket{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[1m])) by (env, instance, operationName, le))",
     "legendFormat": "[{{env}} - {{instance}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(method_timed_seconds_bucket{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[1m])) by (env, instance, operationName, le))",
     "legendFormat": "[{{env}} - {{instance}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(http_server_requests_seconds_bucket{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\", env=\"$env\"}[1m])) by (operationName, dc, pod_name, le))",
     "legendFormat": "[{{pod_name}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "method_timed_seconds{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", quantile=\"$quantile\"}",
     "legendFormat": "[{{env}} - {{instance}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "http_server_requests_seconds{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", quantile=\"$quantile\"}  ",
     "legendFormat": "[{{env}} - {{instance}}] {{operationName}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(http_server_requests_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\"}[1m])) by (operationName, dc, pod_name)",
     "legendFormat": "[{{pod_name}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(method_timed_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\"}[1m])) by (operationName, pod_name, dc)",
     "legendFormat": "[{{pod_name}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(http_server_requests_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (env, instance, operationName)",
     "legendFormat": "[{{dc}} - {{instance}}] {{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(method_timed_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (env, instance, operationName)",
     "legendFormat": "[{{dc}} - {{instance}}] {{operationName}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Status per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "count" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(http_server_requests_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\"}[1m])) by (status) ",
     "legendFormat": "{{status}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(method_timed_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\"$dc.*\", pod_name=~\"$podName\"}[1m])) by (status)",
     "legendFormat": "{{status}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(http_server_requests_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[1m])) by (env, status) ",
     "legendFormat": "{{status}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(method_timed_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[1m])) by (env, status) ",
     "legendFormat": "{{status}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "JVM Total Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (pod_name)",
     "legendFormat": "[{{pod_name}}] used",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_used_bytes{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}) by (env, instance)",
     "legendFormat": "[{{env}} - {{instance}}] used",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_committed_bytes{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (pod_name)",
     "legendFormat": "[{{pod_name}}] commited",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_committed_bytes{env=~\"$dc-$env\", group=~\"$namespace.*\",  service=~\"$applicationName-metrics\", instance=~\"$podName\"}) by (env, instance)",
     "legendFormat": "[{{env}} - {{instance}}] commited",
     "size": 100000
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", area=\"heap\"}) by (pod_name)",
     "legendFormat": "{{pod_name}} used",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_used_bytes{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", area=\"heap\"}) by (instance, env)",
     "legendFormat": "[{{env}} - {{instance}}] used",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_committed_bytes{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", area=\"heap\"}) by (pod_name)",
     "legendFormat": "{{pod_name}} committed",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_committed_bytes{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", area=\"heap\"}) by (env, instance)",
     "legendFormat": "[{{env}} - {{instance}}] commited",
     "size": 100000
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", area=\"nonheap\"}) by (pod_name)",
     "legendFormat": "{{pod_name}} used",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_used_bytes{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", area=\"nonheap\"}) by (instance, env)",
     "legendFormat": "[{{env}} - {{instance}}] used",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_committed_bytes{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", area=\"nonheap\"}) by (pod_name)",
     "legendFormat": "{{pod_name}} committed",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(jvm_memory_committed_bytes{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", area=\"nonheap\"}) by (instance, env)",
     "legendFormat": "[{{env}} - {{instance}}] commited",
     "size": 100000
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(jvm_gc_pause_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[1m])) by(pod_name, cause)",
     "legendFormat": "[{{pod_name}}]  {{cause}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rate(jvm_gc_pause_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[1m])",
     "legendFormat": "[{{env}} - {{instance}}] {{cause}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "GC Pause Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "rate(jvm_gc_pause_seconds_sum{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval]) / rate(jvm_gc_pause_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])",
     "legendFormat": "[{{pod_name}}] avg {{action}} ({{cause}})",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rate(jvm_gc_pause_seconds_sum{env=~\"$dc-$env\",group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval]) / rate(jvm_gc_pause_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])",
     "legendFormat": "[{{env}} {{instance}}] avg {{action}} ({{cause}})",
     "size": 100000
    }
   ]
  },
  {
   "title": "Background processes ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum (increase(method_counted_total{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$__range])) by (operationName)",
     "legendFormat": "{{operationName}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum (increase(method_counted_total{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$__range])) by (operationName)",
     "legendFormat": "{{operationName}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "thread count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "jvm_threads_states_threads{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "[{{pod_name}}] - {{state}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "jvm_threads_states_threads{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "[{{pod_name}}] - {{state}}",
     "size": 100000
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "latency (sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(db_timed_seconds_bucket{db=\"$db\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[1m])) by (pod_name, path, le))",
     "legendFormat": "{{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "db_timed_seconds{db=\"$db\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "{{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(cassandra_timed_seconds_bucket{env=\"$env\", group=~\"$namespace.*\",  container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (pod_name, path, le))",
     "legendFormat": "C* {{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "cassandra_timed_seconds{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\", quantile=\"$quantile\"}",
     "legendFormat": "C* {{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(db_timed_seconds_bucket{db=\"$db\",env=~\"$dc-$env\", group=~\"$namespace.*\",  service=~\"$applicationName-metrics\", instance=~\"$podName\"}[1m])) by (pod_name, path, le))",
     "legendFormat": "{{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "db_timed_seconds{db=\"$db\",env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "{{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(cassandra_timed_seconds_bucket{env=~\"$dc-$env\", group=~\"$namespace.*\",  service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (pod_name, method, le))",
     "legendFormat": "C* {{pod_name}} {{method}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "cassandra_timed_seconds{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "C* {{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(cassandra_timed_seconds_bucket{env=~\"$dc-$env\", group=~\"$namespace.*\",  service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (pod_name, path, le))",
     "legendFormat": "C* {{pod_name}} {{path}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(db_timed_seconds_count{db=\"$db\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (path, pod_name)",
     "legendFormat": "{{pod_name}} - {{path}} ",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(cassandra_timed_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (pod_name, path)",
     "legendFormat": "C* {{pod_name}}  - {{path}} ",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(db_timed_seconds_count{db=\"$db\", env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (path, pod_name)",
     "legendFormat": "{{pod_name}} - {{path}} ",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(cassandra_timed_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (pod_name, method)",
     "legendFormat": "C* {{pod_name}}  - {{method}} ",
     "size": 100000
    }
   ]
  },
  {
   "title": "jdbc connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "jdbc_connections_active{name=\"$db\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - active",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "jdbc_connections_max{name=\"$db\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - max",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "hikaricp_connections_max{env=\"$env\", group=~\"$namespace.*\",  container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - max",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "hikaricp_connections_active{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - active",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "jdbc_connections_active{name=\"$db\",env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - active",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "jdbc_connections_max{name=\"$db\",env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - max",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "hikaricp_connections_max{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - max",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "hikaricp_connections_active{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}} - active",
     "size": 100000
    }
   ]
  },
  {
   "title": "Hikari cp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{env=~\"$env|$dc-$env\", group=~\"$namespace.*\",  service=~\"$applicationName-metrics\", instance=~\"$podName\"} [$interval])) by (pool, pod_name)",
     "legendFormat": " acquire {{pod_name}} {{pool}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{env=~\"$env|$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"} [$interval])) by (pool, pod_name)",
     "legendFormat": " usage {{pod_name}} {{pool}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(hikaricp_connections_creation_seconds_sum{env=~\"$env|$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"} [$interval])) by (pool, pod_name)",
     "legendFormat": " creation {{pod_name}} {{pool}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "hicaricp connection accuire/usage rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"} [$interval])) by (pool, pod_name) /\nsum(rate(hikaricp_connections_usage_seconds_sum{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"} [$interval])) by (pool, pod_name)",
     "legendFormat": "{{pod_name}} - {{pool}} acquire/usage",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{env=~\"$env|$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"} [$interval])) by (pool, pod_name) /\nsum(rate(hikaricp_connections_usage_seconds_sum{env=~\"$env|$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"} [$interval])) by (pool, pod_name)",
     "legendFormat": "{{pod_name}} - {{pool}} acquire/usage",
     "size": 100000
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "latency (sec) rest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(rest_timed_seconds_bucket{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", status=\"success\"}[$interval])) by (path, le, pod_name))",
     "legendFormat": "{{pod_name}} [{{$applicationName}}] {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rest_timed_seconds{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", status=\"success\", quantile=\"$quantile\"}",
     "legendFormat": "{{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(rest_timed_seconds_bucket{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", status=\"success\"}[$interval])) by (path, le, pod_name))",
     "legendFormat": "{{pod_name}} [{{$applicationName}}] {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rest_timed_seconds{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\", status=\"success\", quantile=\"$quantile\"}",
     "legendFormat": "{{pod_name}} [{{$applicationName}}] {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(rest_timed_seconds_bucket{env=~\"$env\", group=~\"$namespace.*\", container_name=~\"$applicationName\", instance=~\"$podName\",}[$interval])) by (path, le, pod_name, status))",
     "legendFormat": "{{pod_name}} [{{$applicationName}}] {{path}} {{status}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(rest_timed_seconds_bucket{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (method, le, pod_name))",
     "legendFormat": "{{pod_name}} [{{$applicationName}}] {{method}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "rest rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(rest_timed_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (path, status, pod_name)",
     "legendFormat": "{{pod_name}} [{{status}}] {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(rest_timed_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (path, status, pod_name)",
     "legendFormat": "{{pod_name}} [{{status}}] {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(rest_timed_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (method, pod_name)",
     "legendFormat": "{{pod_name}} [{{status}}] {{method}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "s3 latency (sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(provider_timed_seconds_bucket{provider=\"s3\",env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (pod_name, path, le))",
     "legendFormat": "[{{pod_name}}] {{path}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "s3 rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(provider_timed_seconds_count{ provider=\"s3\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (path, pod_name, status)",
     "legendFormat": "{{pod_name}} {{path}} [{{status}}]",
     "size": 100000
    }
   ]
  },
  {
   "title": "grpc latency q=$quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "histogram_quantile($quantile, sum(rate(grpc_client_timed_seconds_bucket{status=\"success\",env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (path, le, pod_name))",
     "legendFormat": "{{pod_name}} {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "grpc_client_timed_seconds_bucket{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", quantile=\"$quantile\"}",
     "legendFormat": "{{pod_name}} {{path}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "grpc rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(grpc_client_timed_seconds_count{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (path, status, pod_name)",
     "legendFormat": "{{pod_name}} [{{status}}] {{path}}",
     "size": 100000
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "kafka rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(sender_timed_seconds_bucket{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[1m])) by (pod_name, path, status)",
     "legendFormat": "[{{pod_name}}] {{status}} - {{path}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sender_timed_seconds{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\", quantile=\"$quantile\"}",
     "legendFormat": "[{{pod_name}}] {{status}} - {{path}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "lag records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_consumer_records_lag_records{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (topic, pod_name)",
     "legendFormat": "[{{pod_name}}] {{topic}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Topic lag [Broker]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_consumer_group_lag{group=\"strp\", env=\"prod\", service=\"consumer-lag\", exported_group!=\"kafka.g.lebedev.group\", exported_group!=\"console-consumer-8517\", exported_group!=\"test_kafka_connection\", exported_group=~\"$applicationName.+|.+$applicationName.+|$applicationName\"}) by (topic, exported_group)",
     "size": 100000
    }
   ]
  },
  {
   "title": "Time between poll",
   "type": "graph",
   "description": "The average number of records in each request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_consumer_time_between_poll_max{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (pod_name, client_id)",
     "legendFormat": "{{pod_name}}  - {{client_id}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Record per request",
   "type": "graph",
   "description": "The average number of records in each request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_consumer_fetch_manager_records_per_request_avg{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (pod_name, topic, client_id)",
     "legendFormat": "{{pod_name}} - {{topic}} - {{client_id}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Time the consumer's poll() is idle as opposed",
   "type": "graph",
   "description": "The average fraction of time the consumer's poll() is idle as opposed to waiting for the user code to process records.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_consumer_poll_idle_ratio_avg{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (pod_name, topic, client_id)\n",
     "legendFormat": "{{pod_name}} - {{client_id}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "The maximum number of bytes fetched per request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_consumer_fetch_manager_fetch_size_max{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (pod_name, client_id)",
     "legendFormat": "{{pod_name}} - {{client_id}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Consumer rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(spring_kafka_listener_seconds_count{env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (instance, result)",
     "legendFormat": "[{{instance}}] {{status}} - {{result}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Records per request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "kafka_producer_records_per_request_avg{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "[{{instance}}] {{topic}} {{client_id}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Average batch size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "kafka_producer_batch_size_avg{senv=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "[{{instance}}] {{topic}} {{client_id}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "producer request latency avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_producer_request_latency_avg{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (kafka_name, pod_name, topic, client_id)",
     "legendFormat": "[{{pod_name}}] {{kafka_name}} {{topic}}@{{client_id}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "producer rps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kafka_producer_record_send_rate{env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}) by (pod_name, topic, client_id)",
     "legendFormat": "[{{pod_name}}] {{topic}}@{{client_id}}",
     "size": 100000
    }
   ]
  },
  { "title": "Casandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "cassandra_datastax_open_connections{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}",
     "legendFormat": "[{{pod_name}}] - open",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "cassandra_datastax_trashed_connections{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}",
     "legendFormat": "[{{pod_name}}] - trashed",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "cassandra_datastax_open_connections{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}",
     "legendFormat": "[{{instance}}] - open",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "cassandra_datastax_trashed_connections{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}",
     "legendFormat": "[{{instance}}] - trashed",
     "size": 100000
    }
   ]
  },
  {
   "title": "Bytes transferring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_bytes_received_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
     "legendFormat": "[{{pod_name}}] - received",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_bytes_sent_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
     "legendFormat": "[{{pod_name}}] - sent",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_bytes_received_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
     "legendFormat": "[{{instance}}] - received",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_bytes_sent_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
     "legendFormat": "[{{instance}}] - sent",
     "size": 100000
    }
   ]
  },
  {
   "title": "rps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 233 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_requests_count{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
     "legendFormat": "{{pod_name}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_requests_count{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
     "legendFormat": "{{instance}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "latency ($quantile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 233 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_requests{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\", quantile=\"$quantile\"}[$interval])",
     "legendFormat": "{{pod_name}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "rate(cassandra_datastax_requests{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\", quantile=\"$quantile\"}[$interval])",
     "legendFormat": "{{instance}}",
     "size": 100000
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 } },
  {
   "title": "hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(cache_gets_total{result=\"hit\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (name, pod_name)",
     "legendFormat": "{{pod_name}} {{name}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(cache_gets_total{result=\"hit\", env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (name, pod_name)",
     "legendFormat": "{{pod_name}} {{name}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(cache_gets_total{result=\"miss\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (name, pod_name)",
     "legendFormat": "{{pod_name}} {{name}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "sum(rate(cache_gets_total{result=\"miss\", env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (name, pod_name)",
     "legendFormat": "{{pod_name}} {{name}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "miss / hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 252 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": " (sum(rate(cache_gets_total{result=\"miss\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (name, pod_name)) /\n (sum(rate(cache_gets_total{result=\"hit\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}[$interval])) by (name, pod_name)) ",
     "legendFormat": "{{pod_name}} {{name}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": " (sum(rate(cache_gets_total{result=\"miss\", env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (name, pod_name)) /\n (sum(rate(cache_gets_total{result=\"hit\",env=~\"$dc-$env\", group=~\"$namespace.*\", service=~\"$applicationName-metrics\", instance=~\"$podName\"}[$interval])) by (name, pod_name)) ",
     "legendFormat": "{{pod_name}} {{name}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "cache size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 252 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "cache_size{container_name=\"$applicationName\", env=\"$env\", group=~\"$namespace.*\", container_name=\"$applicationName\", pod_name=~\".*$dc.*\", pod_name=~\"$podName\"}",
     "legendFormat": "({{name}}) {{pod_name}}",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "cache_size{env=~\"$dc-$env\", group=~\"$namespace.*\",  service=~\"$applicationName-metrics\", instance=~\"$podName\"}",
     "legendFormat": "({{name}}) {{instance}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Zipkin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 260 },
   "collapsed": true,
   "panels": [
    {
     "title": "Span rate",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_spans_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - total",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_spans_dropped_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - dropped",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "avg_over_time(zipkin_reporter_queue_spans{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - queue",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_spans_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - total",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_spans_dropped_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - dropped",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_queue_spans{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - queue",
       "size": 100000
      }
     ]
    },
    {
     "title": "Message rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_messages_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - total",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_messages_dropped_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - dropped",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_messages_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - total",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_messages_dropped_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - dropped",
       "size": 100000
      }
     ]
    },
    {
     "title": "Send bytes rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_messages_bytes_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - message",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_spans_bytes_total{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - span",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "avg_over_time(zipkin_reporter_queue_bytes{env=~\"$dc-$env\", instance=~\"$podName\", service=~\"$applicationName.*\"}[$interval])",
       "legendFormat": "[{{instance}}] - queue",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_messages_bytes_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - message",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "rate(zipkin_reporter_spans_bytes_total{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - span",
       "size": 100000
      },
      {
       "chart": "prefix",
       "expr": "avg_over_time(zipkin_reporter_queue_bytes{env=\"$env\", container_name=\"$applicationName\", pod_name=~\"$podName\"}[$interval])",
       "legendFormat": "[{{pod_name}}] - queue",
       "size": 100000
      }
     ]
    }
   ]
  }
 ]
}