{
 "title": "Apps k8s PROD-2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project", "query": "{ //todo replace }.*" },
   { "name": "env", "query": "ds-prod2, m1-prod2, ya-prod1" },
   {
    "name": "namespace",
    "query": "pql label_values(kube_deployment_labels{namespace=~\"{ //todo replace }.*\",env=\"$env\",group=\"k8s\"},namespace)"
   },
   {
    "name": "application",
    "query": "pql label_values(kube_pod_labels{env=\"$env\",namespace=~\"$namespace\",group=\"k8s\"},label_app)"
   },
   {
    "name": "node",
    "query": "pql label_values(kube_pod_info{k8scluster=\"$env\",namespace=\"$namespace\",pod_name=~\".*($application).*\"},node)"
   },
   {
    "name": "node_exporter",
    "query": "pql label_values(kube_pod_info{k8scluster=\"$env\", node=~\"$node\", pod=~\".*(node-exporter).*\"}, pod_name)\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br><br><h3 align=\"center\"><a href=\"https://ui.sage/grafana/d/diB-iCNMk/apps-k8s-prod?orgId=4\">Ссылка</a> на prod</h3>"
   },
   "targets": [
    { "size": 200000, "target": "group=", "type": "timeserie" }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Pods Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "chart": "prefix",
     "expr": "count(sum (kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod)  / count(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod)  == 1 )",
     "size": 100000
    }
   ]
  },
  {
   "title": "Pods Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "chart": "prefix",
     "expr": "count(kube_pod_created{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"})",
     "size": 100000
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"})",
     "size": 100000
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}))",
     "size": 100000
    }
   ]
  },
  {
   "title": "Per Pod Statistic",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql step=1h sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"})) by (pod)\n| rename value as cpu_usage\n| fields pod, cpu_usage",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql step=1h sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"})  by(pod)\n| rename value as mem_used\n| fields pod, mem_used",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql step=1h kube_pod_status_phase{namespace=\"$namespace\", pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"} == 1\n| fields pod, phase",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql step=1h sum (kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod)  /  count(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod)  == 1 \n| rename value as readiness\n| fields pod,  readiness",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql step=1h time()  - kube_pod_start_time{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"} \n| rename value as pod_age\n| fields pod, pod_age",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql step=1h time() - container_start_time_seconds{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\",container_name!=\"\"} \n| stats min(value) as uptime by pod \n| fields pod, uptime",
     "size": 100000
    }
   ]
  },
  { "title": "Pods Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pod Readiness",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod)  /  count(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod)\n",
     "size": 100000
    }
   ]
  },
  {
   "title": "Pod Termination Reasons ",
   "type": "flant-statusmap-panel",
   "description": "Каждая красная линия это смерть контейнера. \nОбычно после этого идет перезапуск конейнера, но не всегда",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql kube_pod_container_status_last_terminated_reason{reason!~\"Completed\", group=~\"k8s\",namespace=~\"$namespace\",pod=~\"(ds-|m1-)*($application).*\",env=\"$env\"} > 0\n  and \n  on(container, pod) increase(kube_pod_container_status_restarts_total{group=~\"k8s\",namespace=~\"$namespace\",pod=~\"(ds-|m1-)*($application).*\",env=\"$env\"}[30s]) > 0\n| timechart latest(value) by pod, reason",
     "legendFormat": "{{  pod_name }}",
     "size": 100000
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}[1m])) by (pod)\n| timechart limit=0 sum(value) by pod",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod)\n| timechart limit=0  mean(value) as requested",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\", resource=\"cpu\"}) by (pod)\n| timechart limit=0  mean(value) as limits",
     "size": 100000
    }
   ]
  },
  {
   "title": "CPU Throttling ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\",env=\"$env\"})\n| timechart limit=0 sum(value) by pod",
     "size": 100000
    }
   ]
  },
  {
   "title": "CPU Throttling % (t_periods/periods)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "100 * sum(increase(container_cpu_cfs_throttled_periods_total{env=\"$env\",namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\"}[5m])) by (pod, container) / sum(increase(container_cpu_cfs_periods_total{env=\"$env\",namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\"}[5m])) by (pod, container)",
     "legendFormat": "{{pod}}@{{container}}",
     "size": 100000
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql  sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}) by (pod) \n| timechart limit=0 sum(value) by pod",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql sum by(pod) (kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\", resource=\"memory\"})\n| timechart  mean(value) as requested",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql sum by(pod) (kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\", resource=\"memory\"})\n| timechart  mean(value) as limit",
     "size": 100000
    }
   ]
  },
  { "title": "Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}[5s])) \n| eval legend =  \"RX: \" + pod\n| timechart  sum(value) by legend",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql  (sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"(ds-|m1-)*($application).*\", env=\"$env\"}[5s]))) * -1\n| eval legend =  \"TX: \" + pod\n| timechart  sum(value) by legend",
     "size": 100000
    }
   ]
  },
  {
   "title": "Statistics by $application nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 }
  },
  {
   "title": "Memory $node_exporter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "repeat": "node_exporter",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"} - node_memory_MemFree_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"} - node_memory_Cached_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"}) / (node_memory_MemTotal_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"} )) * 100",
     "legendFormat": "{{ instance }}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Memory $node_exporter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"} - node_memory_MemFree_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"} - node_memory_Cached_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"}) / (node_memory_MemTotal_bytes{instance=~\"$node_exporter\", k8scluster=\"$env\"} )) * 100",
     "legendFormat": "{{ instance }}",
     "size": 100000
    }
   ]
  },
  {
   "title": "System load $node_exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 93 },
   "repeat": "node_exporter",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "avg(node_load1{instance=~\"$node_exporter\", k8scluster=\"$env\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node_exporter\", k8scluster=\"$env\"}) by (cpu)) * 100",
     "size": 100000
    }
   ]
  },
  {
   "title": "System load $node_exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "avg(node_load1{instance=~\"$node_exporter\", k8scluster=\"$env\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node_exporter\", k8scluster=\"$env\"}) by (cpu)) * 100",
     "size": 100000
    }
   ]
  },
  {
   "title": "Pods for $node",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql sum(rate(container_cpu_usage_seconds_total{env=\"$env\", instance=\"$node\"})) by (pod) \n| stats last(value) by pod",
     "size": 100000
    }
   ]
  },
  {
   "title": "Pods for $node",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql sum(rate(container_cpu_usage_seconds_total{env=\"$env\", instance=\"$node\"})) by (pod) \n| stats last(value) by pod",
     "size": 100000
    }
   ]
  },
  { "title": "Istio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Istio RPM - Logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "group='{ //todo replace }' or group=\"{ //todo replace }\" system=\"istio-ingress\"  env=\"$env\" upstream_cluster:\".*$application.*{ //todo replace }.*\"\n| eval legend =  response_flags + \" \" + status + \" \" + vhost\n| timechart span=10s   count by legend",
     "size": 100000
    }
   ]
  },
  {
   "title": "Cluster request latency (P99, P95, P50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{k8scluster!=\"\",env=\"$env\",cluster_name=~\".*($application).*{ //todo replace }.*\"}[1m])) by (le, cluster_name))\n| eval legend = \"p99 \" + cluster_name \n| timechart  max(value) by legend",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{k8scluster!=\"\",env=\"$env\",cluster_name=~\".*($application).*{ //todo replace }.*\"}[1m])) by (le, cluster_name))\n| eval legend = \"p95 \" + cluster_name \n| timechart  max(value) by legend",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql histogram_quantile(0.50, sum(rate(envoy_cluster_upstream_rq_time_bucket{k8scluster!=\"\",env=\"$env\",cluster_name=~\".*($application).*{ //todo replace }.*\"}[1m])) by (le, cluster_name))\n| eval legend = \"p50 \" + cluster_name \n| timechart  max(value) by legend",
     "size": 100000
    }
   ]
  },
  {
   "title": "Istio RPS by code - Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql step=10s sum(rate(envoy_cluster_upstream_rq{k8scluster!=\"\",env=\"$env\",cluster_name=~\".*($application).*{ //todo replace }.*\"}[1m])) by (cluster_name, response_code_class)\n| eval legend = response_code_class + \" \" + cluster_name\n| timechart  span=10s  max(value) by legend",
     "size": 100000
    }
   ]
  },
  {
   "title": "Traffic In/Out ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "chart": "prefix",
     "expr": "pql step=10s sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{k8scluster!=\"\",env=\"$env\",cluster_name=~\"outbound\\\\|.*($application).*{ //todo replace }.*\"}[1m]) ) by (cluster_name) != 0\n| eval legend = \"RX \" + cluster_name\n| timechart  span=10s  max(value) by legend",
     "size": 100000
    },
    {
     "chart": "prefix",
     "expr": "pql step=10s sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{k8scluster!=\"\",env=\"$env\",cluster_name=~\"outbound\\\\|.*($application).*{ //todo replace }.*\"}[1m]) ) by (cluster_name)* -1\n| eval legend = \"TX \" + cluster_name\n| timechart  span=10s  max(value) by legend",
     "size": 100000
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentile per Level",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 149 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "chart": "prefix",
       "expr": "group=\"{ //todo replace }\" or group=\"{ //todo replace }\" system=\"$namespace\" kubernetes.pod.name:\".*$application.*\" env=\"$env\"\n| timechart count by level",
       "size": 100000
      }
     ]
    },
    {
     "title": "Logs flow",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "chart": "prefix",
       "expr": "group=\"{ //todo replace }\" or group=\"{ //todo replace }\" system=\"$namespace\" kubernetes.pod.name:\".*$application.*\" env=\"$env\" \n| timechart   count as Messages",
       "size": 100000
      }
     ]
    }
   ]
  },
  {
   "title": "Log Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 157 },
     "options": {
      "content": "<iframe src=\"https://ui.sage/search?query=group%3D'{ //todo replace }'%20or%20group%3D'{ //todo replace }'%20system%3D%22$namespace%22%20kubernetes.pod.name:%22.*$application.*%22%20env%3D%22${env}%22&start=-30m&end=now&activeTabIndex=1\" width=\"100%\" height=\"100%\" style=\"background-color: #FFFFFF\"></iframe>"
     },
     "content": "<iframe src=\"https://ui.sage/search?query=group%3D'{ //todo replace }'%20or%20group%3D'{ //todo replace }'%20system%3D%22$namespace%22%20kubernetes.pod.name:%22.*$application.*%22%20env%3D%22${env}%22&start=-30m&end=now&activeTabIndex=1\" width=\"100%\" height=\"100%\" style=\"background-color: #FFFFFF\"></iframe>",
     "targets": [
      { "size": 200000, "target": "group=", "type": "timeserie" }
     ]
    }
   ]
  }
 ]
}