scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: spring-actuator
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]